version: 2.1

workflows:
   test-deploy:
     jobs:
       - test

jobs:
  test:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: |
            npm install --save
      - node/install-packages
      - run :
         name: Run Tests
         command : npm run test